//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClubLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAttendance
    {
        public int AttendanceId { get; set; }
        public Nullable<int> MemberOfferId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public string ReplacedBy { get; set; }
    
        public virtual MemberOffer MemberOffer { get; set; }
        public virtual service service { get; set; }
    }
}
