//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClub.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public int AuditId { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public Nullable<int> ActionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> TransactionTime { get; set; }
        public Nullable<int> EntityId { get; set; }
        public string EntityRecord { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual ActionType ActionType { get; set; }
        public virtual MasterEntity MasterEntity { get; set; }
    }
}
