//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClub.UI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyClubDBEntities : DbContext
    {
        public MyClubDBEntities()
            : base("name=MyClubDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<ActionType> ActionTypes { get; set; }
        public virtual DbSet<AuditTrail> AuditTrails { get; set; }
        public virtual DbSet<MasterEntity> MasterEntities { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberAttendance> MemberAttendances { get; set; }
        public virtual DbSet<MemberOffer> MemberOffers { get; set; }
        public virtual DbSet<OfferDetail> OfferDetails { get; set; }
        public virtual DbSet<OfferDuration> OfferDurations { get; set; }
        public virtual DbSet<OfferPrice> OfferPrices { get; set; }
        public virtual DbSet<OfferPricelid> OfferPricelids { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
        public virtual DbSet<User_Profile> User_Profiles { get; set; }
        public virtual DbSet<WebPages_Pages> WebPages_Pages { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<webPages_UserPermessions> webPages_UserPermessions { get; set; }
    }
}
