//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClub.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferPricelid
    {
        public int OfferPricelidId { get; set; }
        public Nullable<int> OfferPriceId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual OfferPrice OfferPrice { get; set; }
    }
}
