//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClub.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferDuration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfferDuration()
        {
            this.OfferPrices = new HashSet<OfferPrice>();
        }
    
        public int OfferDurationId { get; set; }
        public string OfferDurationName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<int> Days { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferPrice> OfferPrices { get; set; }
    }
}
