//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClub.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webPages_UserPermessions
    {
        public int UserPageID { get; set; }
        public int UserID { get; set; }
        public int Pageid { get; set; }
        public bool CanRead { get; set; }
    
        public virtual User_Profile User_Profile { get; set; }
        public virtual WebPages_Pages WebPages_Pages { get; set; }
    }
}
